### ISSUE TITLE
adding podcasts?

### ISSUE THREAD

**Issue by jyng** [terra-cotta-collective/terracottacollective.org#11]
Hey Ferris,
just found about this. I thought about making a one-pager, but looks like you're a lot farther ahead than i am.

Just curious where audio/video content would fit? (ie: https://bumpers.fm/sweetandsour)

**Comment by jyng** [comment]
Oh nvm, i overlooked the Other section

**Comment by jyng** [comment]
Found another podcast! https://www.swayfpodcast.com/

**Comment by ferristseng** [comment]
Cool! I will add these. I think if the section grows large enough, we can plan on splitting it out into a separate section.

**Comment by ferristseng** [comment]
Added these, thank you!
